-- edgeweir.probehealth: the health endpoint of the edge listeners for the
-- console's regional probes (feature probe-health-v1).
--
-- GET (or HEAD) /.edgeweir/health is answered "200 ok" (text/plain,
-- Cache-Control: no-store) at the very start of the edge access phase,
-- for any Host: before CDN-Loop, HTTP-01 answers, the site lookup, bans,
-- rules and CC. It never reaches the cache or an origin, and site
-- statistics and sampled access logs skip it (they need a site).
--
-- TLS: handshakes with SNI health.edgeweir.invalid, or without SNI, get
-- the node's self-signed health certificate (generated by the agent and
-- pushed with the site table as health_certificate; edgeweir.tls). Such a
-- connection reaches nothing but the health path: any other request is
-- answered 421 (sni-host-mismatch) before anything else runs.
local _M = {}

local lower = string.lower

_M.PATH = "/.edgeweir/health"
_M.SNI = "health.edgeweir.invalid"

-- is_request reports whether a request (method, normalized $uri) asks for
-- the health endpoint.
function _M.is_request(method, uri)
  return uri == _M.PATH and (method == "GET" or method == "HEAD")
end

-- is_health_sni reports whether a TLS server name selects the health
-- certificate: health.edgeweir.invalid in any case, or no name at all.
function _M.is_health_sni(name)
  return name == nil or name == "" or lower(name) == _M.SNI
end

-- material returns the health certificate of a table's settings (from
-- edgeweir.store.config), or nil.
function _M.material(cfg)
  local m = cfg and cfg.health_certificate
  if type(m) == "table" and type(m.chain_pem) == "string" and m.chain_pem ~= ""
    and type(m.private_key_pem) == "string" and m.private_key_pem ~= ""
    and type(m.fingerprint) == "string" and m.fingerprint ~= "" then
    return m
  end
  return nil
end

-- respond answers the health request with a fixed length (never chunked;
-- nginx drops the body for HEAD).
function _M.respond()
  ngx.status = ngx.HTTP_OK
  ngx.header["Content-Type"] = "text/plain"
  ngx.header["Content-Length"] = 2
  ngx.header["Cache-Control"] = "no-store"
  ngx.print("ok")
  return ngx.exit(ngx.HTTP_OK)
end

return _M
