package render

import (
	"bytes"
	"flag"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"github.com/edgeweir/edgeweir-node/internal/configir"
)

var update = flag.Bool("update", false, "rewrite golden files")

func params() Params {
	return Params{
		Prefix:        "/var/lib/edgeweir-node/nginx",
		LuaDir:        "/usr/share/edgeweir-node/lua",
		CacheDir:      "/var/cache/edgeweir-node",
		ControlSocket: "/run/edgeweir-node/control.sock",
		OriginSocket:  "/run/edgeweir-node/origin.sock",
		ResolvConf:    "/etc/resolv.conf",
		Resolvers:     []string{"127.0.0.11"},
	}
}

func golden(t *testing.T, name string, got []byte) {
	t.Helper()
	path := filepath.Join("testdata", name)
	if *update {
		if err := os.WriteFile(path, got, 0o644); err != nil {
			t.Fatal(err)
		}
	}
	want, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read golden file (run with -update): %v", err)
	}
	if !bytes.Equal(got, want) {
		t.Fatalf("%s differs from golden file; run `go test ./internal/render -update` and review the diff\n--- got ---\n%s", name, got)
	}
}

func TestRenderBootstrapGolden(t *testing.T) {
	got, err := Render(params(), configir.Bootstrap(80))
	if err != nil {
		t.Fatal(err)
	}
	golden(t, "bootstrap.conf.golden", got)
}

func TestRenderFullGolden(t *testing.T) {
	p := params()
	p.Resolvers = []string{"10.0.0.2", "[2001:db8::53]"}
	p.ResolverIPv6 = true
	p.ListenIPv6 = true
	p.WorkerConnections = 8192
	p.WorkerRlimitNofile = 65536
	p.TrustedCA = "/etc/ssl/certs/ca-certificates.crt"
	plan := &configir.Plan{
		Listeners: []configir.Listener{
			{Port: 80, HTTP2: true},
			{Port: 8080, ProxyProtocol: true},
		},
		CacheZones: []configir.CacheZone{
			{Name: "hot", MaxSizeMB: 2048, KeysZoneMB: 32, InactiveSeconds: 86400},
			{Name: "images", MaxSizeMB: 10240, KeysZoneMB: 64, InactiveSeconds: 3600},
		},
		Sites: []configir.Site{{ID: "must-not-appear-in-nginx-conf"}},
	}
	got, err := Render(p, plan)
	if err != nil {
		t.Fatal(err)
	}
	if bytes.Contains(got, []byte("must-not-appear")) {
		t.Fatal("site data leaked into nginx.conf")
	}
	golden(t, "full.conf.golden", got)
}

func TestRenderIgnoresSitesAndRevision(t *testing.T) {
	a := configir.Bootstrap(80)
	b := configir.Bootstrap(80)
	b.Revision = 42
	b.ContentHash = "abc"
	b.Sites = []configir.Site{{ID: "s1", Domains: []configir.Domain{{Name: "a.test"}}}}
	ra, _ := Render(params(), a)
	rb, _ := Render(params(), b)
	if !bytes.Equal(ra, rb) {
		t.Fatal("site or revision changes altered nginx.conf (would trigger needless reloads)")
	}
	c := configir.Bootstrap(8080)
	rc, _ := Render(params(), c)
	if bytes.Equal(ra, rc) {
		t.Fatal("listener change did not alter nginx.conf")
	}
}

func TestRenderRejectsUnsafeInput(t *testing.T) {
	bad := []func(*Params){
		func(p *Params) { p.Prefix = "relative/path" },
		func(p *Params) { p.LuaDir = "/usr/share/lua; include /etc/passwd" },
		func(p *Params) { p.ControlSocket = "/run/x sock" },
		func(p *Params) { p.Resolvers = []string{"8.8.8.8 valid=1s"} },
		func(p *Params) { p.Resolvers = []string{"dns.example"} },
		func(p *Params) { p.WorkerProcesses = "auto;" },
		func(p *Params) { p.User = "root; daemon on" },
		func(p *Params) { p.TrustedCA = "/etc/ssl/ca.pem; include /etc/passwd" },
		func(p *Params) { p.OriginSocketNoVerify = p.OriginSocket },
		func(p *Params) { p.EdgeSocket = "/run/edge sock" },
		func(p *Params) { p.PurgeDictMB = 100000 },
		func(p *Params) { p.PurgeDictMB = -1 },
	}
	for i, mutate := range bad {
		p := params()
		mutate(&p)
		if _, err := Render(p, configir.Bootstrap(80)); err == nil {
			t.Errorf("case %d: unsafe params accepted", i)
		}
	}
	plan := configir.Bootstrap(80)
	plan.CacheZones[0].Name = "x; evil"
	if _, err := Render(params(), plan); err == nil {
		t.Error("unsafe zone name accepted")
	}
	if _, err := Render(params(), &configir.Plan{}); err == nil {
		t.Error("empty plan accepted")
	}
}

func TestParseResolvConf(t *testing.T) {
	in := `# Generated by Docker
search example.internal
nameserver 127.0.0.11
options ndots:0
nameserver 2001:4860:4860::8888
nameserver fe80::1%eth0
nameserver ::ffff:10.0.0.1
nameserver 127.0.0.11
nameserver not-an-ip
nameserver 0.0.0.0
  nameserver 1.1.1.1 # trailing comment
`
	got := ParseResolvConf(strings.NewReader(in))
	want := []string{"127.0.0.11", "[2001:4860:4860::8888]", "10.0.0.1", "1.1.1.1"}
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("ParseResolvConf = %v, want %v", got, want)
	}
}

func TestResolversFallback(t *testing.T) {
	if got := Resolvers(filepath.Join(t.TempDir(), "missing")); !reflect.DeepEqual(got, []string{"127.0.0.1"}) {
		t.Fatalf("missing file: %v", got)
	}
	empty := filepath.Join(t.TempDir(), "resolv.conf")
	if err := os.WriteFile(empty, []byte("search x\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if got := Resolvers(empty); !reflect.DeepEqual(got, []string{"127.0.0.1"}) {
		t.Fatalf("no nameservers: %v", got)
	}
}

func TestRenderOriginLayersAndTrustStore(t *testing.T) {
	p := params()
	got, err := Render(p, configir.Bootstrap(80))
	if err != nil {
		t.Fatal(err)
	}
	conf := string(got)
	for _, want := range []string{
		"listen unix:/run/edgeweir-node/origin.sock;",
		"listen unix:/run/edgeweir-node/origin-noverify.sock;",
		"proxy_ssl_verify off;",
		`set $edgeweir_trust_store "missing";`,
		"balancer_by_lua_block",
		"lua_shared_dict edgeweir_purge 32m;",
		`resolvers = {"127.0.0.11"},`,
	} {
		if !strings.Contains(conf, want) {
			t.Errorf("nginx.conf lacks %q", want)
		}
	}
	// Without a CA bundle the verifying layer must not claim to verify.
	if strings.Contains(conf, "proxy_ssl_verify on;") {
		t.Error("proxy_ssl_verify on without a trusted certificate")
	}
	p.TrustedCA = "/etc/ssl/certs/ca-certificates.crt"
	got, err = Render(p, configir.Bootstrap(80))
	if err != nil {
		t.Fatal(err)
	}
	conf = string(got)
	if strings.Count(conf, "proxy_ssl_verify on;") != 1 || strings.Count(conf, "proxy_ssl_verify off;") != 1 ||
		!strings.Contains(conf, "proxy_ssl_trusted_certificate /etc/ssl/certs/ca-certificates.crt;") ||
		!strings.Contains(conf, `set $edgeweir_trust_store "ok";`) {
		t.Errorf("verifying origin layer not rendered as expected:\n%s", conf)
	}
}

// TestRenderOriginTLSName pins the directives that make origin HTTPS
// verification check the origin's own name (N-H4): the name comes from
// $edgeweir_ssl_name (set per attempt in balancer_by_lua), SNI is sent,
// the verifying layer checks the certificate against the trusted CA, and
// nginx's default upstream connection cache (nginx >= 1.29.7, matched on
// the address only) is off so a connection verified for one name is never
// reused for another.
func TestRenderOriginTLSName(t *testing.T) {
	p := params()
	p.TrustedCA = "/etc/edgeweir/origin-ca.pem"
	got, err := Render(p, configir.Bootstrap(80))
	if err != nil {
		t.Fatal(err)
	}
	conf := string(got)
	balancer := section(t, conf, "upstream edgeweir_balancer {", "}")
	if !strings.Contains(balancer, "keepalive 0;") {
		t.Errorf("balancer upstream keeps nginx's default connection cache:\n%s", balancer)
	}
	layers := strings.Split(conf, "listen unix:")
	var verify, noverify string
	for _, l := range layers {
		switch {
		case strings.HasPrefix(l, "/run/edgeweir-node/origin.sock;"):
			verify = l
		case strings.HasPrefix(l, "/run/edgeweir-node/origin-noverify.sock;"):
			noverify = l
		}
	}
	for name, layer := range map[string]string{"verify": verify, "noverify": noverify} {
		for _, want := range []string{
			`set $edgeweir_ssl_name "";`,
			"proxy_ssl_name $edgeweir_ssl_name;",
			"proxy_ssl_server_name on;",
		} {
			if !strings.Contains(layer, want) {
				t.Errorf("%s origin layer lacks %q", name, want)
			}
		}
	}
	for _, want := range []string{"proxy_ssl_verify on;", "proxy_ssl_trusted_certificate /etc/edgeweir/origin-ca.pem;"} {
		if !strings.Contains(verify, want) {
			t.Errorf("verifying origin layer lacks %q", want)
		}
	}
	if !strings.Contains(noverify, "proxy_ssl_verify off;") {
		t.Error("origin layer without verification does not turn it off")
	}
}

// section returns the text from start up to the first end after it.
func section(t *testing.T, s, start, end string) string {
	t.Helper()
	i := strings.Index(s, start)
	if i < 0 {
		t.Fatalf("%q not found", start)
	}
	j := strings.Index(s[i:], end)
	if j < 0 {
		t.Fatalf("%q not closed", start)
	}
	return s[i : i+j+len(end)]
}

// TestRenderPurgeDictSize: the purge marker store size comes from
// --purge-dict-mb.
func TestRenderPurgeDictSize(t *testing.T) {
	p := params()
	p.PurgeDictMB = 128
	got, err := Render(p, configir.Bootstrap(80))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(got), "lua_shared_dict edgeweir_purge 128m;") {
		t.Fatal("purge dict size not rendered")
	}
}

// TestRenderProxyProtocolRealIP: behind a PROXY protocol listener the
// client address from the header is $remote_addr (what origins and logs
// see); plain listeners keep the peer address. The local edge socket for
// prefetches never expects the PROXY protocol.
func TestRenderProxyProtocolRealIP(t *testing.T) {
	plan := &configir.Plan{
		Listeners:  []configir.Listener{{Port: 80}, {Port: 8080, ProxyProtocol: true}},
		CacheZones: []configir.CacheZone{{Name: "z", MaxSizeMB: 1, KeysZoneMB: 1, InactiveSeconds: 60}},
	}
	got, err := Render(params(), plan)
	if err != nil {
		t.Fatal(err)
	}
	conf := string(got)
	plain := section(t, conf, "listen 80 default_server;", "location /")
	pp := section(t, conf, "listen 8080 default_server proxy_protocol;", "location /")
	local := section(t, conf, "listen unix:/run/edgeweir-node/edge.sock default_server;", "location /")
	for _, want := range []string{"set_real_ip_from 0.0.0.0/0;", "set_real_ip_from ::/0;", "real_ip_header proxy_protocol;"} {
		if !strings.Contains(pp, want) {
			t.Errorf("PROXY protocol listener lacks %q", want)
		}
		if strings.Contains(plain, want) || strings.Contains(local, want) {
			t.Errorf("plain or local listener has %q", want)
		}
	}
	if strings.Contains(local, "proxy_protocol") {
		t.Error("local edge socket expects the PROXY protocol")
	}
}
