package render

import (
	"bytes"
	"flag"
	"maps"
	"os"
	"path/filepath"
	"reflect"
	"regexp"
	"slices"
	"strings"
	"testing"

	"github.com/marvinli001/edgeweir-node/internal/configir"
	nodev1 "github.com/marvinli001/edgeweir-node/internal/gen/edgeweir/node/v1"
)

var update = flag.Bool("update", false, "rewrite golden files")

func params() Params {
	return Params{
		Prefix:        "/var/lib/edgeweir-node/nginx",
		LuaDir:        "/usr/share/edgeweir-node/lua",
		CacheDir:      "/var/cache/edgeweir-node",
		ControlSocket: "/run/edgeweir-node/control.sock",
		OriginSocket:  "/run/edgeweir-node/origin.sock",
		ResolvConf:    "/etc/resolv.conf",
		Resolvers:     []string{"127.0.0.11"},
	}
}

func golden(t *testing.T, name string, got []byte) {
	t.Helper()
	path := filepath.Join("testdata", name)
	if *update {
		if err := os.WriteFile(path, got, 0o644); err != nil {
			t.Fatal(err)
		}
	}
	want, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read golden file (run with -update): %v", err)
	}
	if !bytes.Equal(got, want) {
		t.Fatalf("%s differs from golden file; run `go test ./internal/render -update` and review the diff\n--- got ---\n%s", name, got)
	}
}

func TestRenderBootstrapGolden(t *testing.T) {
	got, err := Render(params(), configir.Bootstrap(80))
	if err != nil {
		t.Fatal(err)
	}
	golden(t, "bootstrap.conf.golden", got)
}

func TestRenderFullGolden(t *testing.T) {
	p := params()
	p.Resolvers = []string{"10.0.0.2", "[2001:db8::53]"}
	p.ResolverIPv6 = true
	p.ListenIPv6 = true
	p.WorkerConnections = 8192
	p.WorkerRlimitNofile = 65536
	p.TrustedCA = "/etc/ssl/certs/ca-certificates.crt"
	plan := &configir.Plan{
		Listeners: []configir.Listener{
			{Port: 80, HTTP2: true},
			{Port: 8080, ProxyProtocol: true},
		},
		CacheZones: []configir.CacheZone{
			{Name: "hot", MaxSizeMB: 2048, KeysZoneMB: 32, InactiveSeconds: 86400},
			{Name: "images", MaxSizeMB: 10240, KeysZoneMB: 64, InactiveSeconds: 3600},
		},
		Sites: []configir.Site{{ID: "must-not-appear-in-nginx-conf"}},
	}
	got, err := Render(p, plan)
	if err != nil {
		t.Fatal(err)
	}
	if bytes.Contains(got, []byte("must-not-appear")) {
		t.Fatal("site data leaked into nginx.conf")
	}
	golden(t, "full.conf.golden", got)
}

func TestRenderIgnoresHotSiteFieldsAndRevision(t *testing.T) {
	a := configir.Bootstrap(80)
	a.Sites = []configir.Site{{ID: "s1"}}
	b := configir.Bootstrap(80)
	b.Revision = 42
	b.ContentHash = "abc"
	b.Sites = []configir.Site{{ID: "s1", Domains: []configir.Domain{{Name: "a.test"}}}}
	ra, _ := Render(params(), a)
	rb, _ := Render(params(), b)
	if !bytes.Equal(ra, rb) {
		t.Fatal("hot site fields or revision altered nginx.conf")
	}
	b.Sites = append(b.Sites, configir.Site{ID: "s2"})
	rb, _ = Render(params(), b)
	if bytes.Equal(ra, rb) {
		t.Fatal("new site did not reserve an independent counter partition")
	}
	c := configir.Bootstrap(8080)
	rc, _ := Render(params(), c)
	if bytes.Equal(ra, rc) {
		t.Fatal("listener change did not alter nginx.conf")
	}
}

func TestRenderRejectsUnsafeInput(t *testing.T) {
	bad := []func(*Params){
		func(p *Params) { p.Prefix = "relative/path" },
		func(p *Params) { p.LuaDir = "/usr/share/lua; include /etc/passwd" },
		func(p *Params) { p.ControlSocket = "/run/x sock" },
		func(p *Params) { p.Resolvers = []string{"8.8.8.8 valid=1s"} },
		func(p *Params) { p.Resolvers = []string{"dns.example"} },
		func(p *Params) { p.WorkerProcesses = "auto;" },
		func(p *Params) { p.User = "root; daemon on" },
		func(p *Params) { p.TrustedCA = "/etc/ssl/ca.pem; include /etc/passwd" },
		func(p *Params) { p.OriginSocketNoVerify = p.OriginSocket },
		func(p *Params) { p.OriginSocketH2 = p.OriginSocket },
		func(p *Params) { p.OriginSocketNoVerifyGRPC = "/run/edgeweir-node/origin-h2.sock" },
		func(p *Params) { p.OriginSocketGRPC = "/run/grpc sock" },
		func(p *Params) { p.EdgeSocket = "/run/edge sock" },
		func(p *Params) { p.PurgeDictMB = 100000 },
		func(p *Params) { p.PurgeDictMB = -1 },
		func(p *Params) { p.BanDictMB = 70000 },
		func(p *Params) { p.BanDictMB = -2 },
		func(p *Params) { p.BanCapacity = -1 },
		func(p *Params) { p.BanCapacity = MaxBanCapacity + 1 },
	}
	for i, mutate := range bad {
		p := params()
		mutate(&p)
		if _, err := Render(p, configir.Bootstrap(80)); err == nil {
			t.Errorf("case %d: unsafe params accepted", i)
		}
	}
	plan := configir.Bootstrap(80)
	plan.CacheZones[0].Name = "x; evil"
	if _, err := Render(params(), plan); err == nil {
		t.Error("unsafe zone name accepted")
	}
	if _, err := Render(params(), &configir.Plan{}); err == nil {
		t.Error("empty plan accepted")
	}
}

func TestParseResolvConf(t *testing.T) {
	in := `# Generated by Docker
search example.internal
nameserver 127.0.0.11
options ndots:0
nameserver 2001:4860:4860::8888
nameserver fe80::1%eth0
nameserver ::ffff:10.0.0.1
nameserver 127.0.0.11
nameserver not-an-ip
nameserver 0.0.0.0
  nameserver 1.1.1.1 # trailing comment
`
	got := ParseResolvConf(strings.NewReader(in))
	want := []string{"127.0.0.11", "[2001:4860:4860::8888]", "10.0.0.1", "1.1.1.1"}
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("ParseResolvConf = %v, want %v", got, want)
	}
}

func TestResolversFallback(t *testing.T) {
	if got := Resolvers(filepath.Join(t.TempDir(), "missing")); !reflect.DeepEqual(got, []string{"127.0.0.1"}) {
		t.Fatalf("missing file: %v", got)
	}
	empty := filepath.Join(t.TempDir(), "resolv.conf")
	if err := os.WriteFile(empty, []byte("search x\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if got := Resolvers(empty); !reflect.DeepEqual(got, []string{"127.0.0.1"}) {
		t.Fatalf("no nameservers: %v", got)
	}
}

func TestRenderOriginLayersAndTrustStore(t *testing.T) {
	p := params()
	got, err := Render(p, configir.Bootstrap(80))
	if err != nil {
		t.Fatal(err)
	}
	conf := string(got)
	for _, want := range []string{
		"listen unix:/run/edgeweir-node/origin.sock;",
		"listen unix:/run/edgeweir-node/origin-noverify.sock;",
		"listen unix:/run/edgeweir-node/origin-h2.sock;",
		"listen unix:/run/edgeweir-node/origin-noverify-h2.sock;",
		"listen unix:/run/edgeweir-node/origin-grpc.sock;",
		"listen unix:/run/edgeweir-node/origin-noverify-grpc.sock;",
		"proxy_ssl_verify off;",
		"grpc_ssl_verify off;",
		`set $edgeweir_trust_store "missing";`,
		"balancer_by_lua_block",
		"lua_shared_dict edgeweir_purge 32m;",
		`resolvers = {"127.0.0.11"},`,
	} {
		if !strings.Contains(conf, want) {
			t.Errorf("nginx.conf lacks %q", want)
		}
	}
	// Without a CA bundle the verifying layers must not claim to verify.
	if strings.Contains(conf, "proxy_ssl_verify on;") || strings.Contains(conf, "grpc_ssl_verify on;") {
		t.Error("TLS verification on without a trusted certificate")
	}
	p.TrustedCA = "/etc/ssl/certs/ca-certificates.crt"
	got, err = Render(p, configir.Bootstrap(80))
	if err != nil {
		t.Fatal(err)
	}
	conf = string(got)
	// HTTP/1.1 and HTTP/2 layers use the proxy module, gRPC layers grpc;
	// every layer has the location / and the one without status retries.
	if strings.Count(conf, "proxy_ssl_verify on;") != 4 || strings.Count(conf, "proxy_ssl_verify off;") != 4 ||
		strings.Count(conf, "grpc_ssl_verify on;") != 2 || strings.Count(conf, "grpc_ssl_verify off;") != 2 ||
		strings.Count(conf, "proxy_ssl_trusted_certificate /etc/ssl/certs/ca-certificates.crt;") != 4 ||
		strings.Count(conf, "grpc_ssl_trusted_certificate /etc/ssl/certs/ca-certificates.crt;") != 2 ||
		strings.Count(conf, `set $edgeweir_trust_store "ok";`) != 12 {
		t.Errorf("verifying origin layers not rendered as expected:\n%s", conf)
	}
}

// TestRenderOriginTLSName pins the directives that make origin HTTPS
// verification check the origin's own name (N-H4): the name comes from
// $edgeweir_ssl_name (set per attempt in balancer_by_lua), SNI is sent,
// the verifying layer checks the certificate against the trusted CA, and
// nginx's default upstream connection cache (nginx >= 1.29.7, matched on
// the address only) is off so a connection verified for one name is never
// reused for another.
func TestRenderOriginTLSName(t *testing.T) {
	p := params()
	p.TrustedCA = "/etc/edgeweir/origin-ca.pem"
	got, err := Render(p, configir.Bootstrap(80))
	if err != nil {
		t.Fatal(err)
	}
	conf := string(got)
	for _, name := range []string{"edgeweir_balancer", "edgeweir_balancer_h2", "edgeweir_balancer_grpc"} {
		balancer := section(t, conf, "upstream "+name+" {", "}")
		if !strings.Contains(balancer, "keepalive 0;") {
			t.Errorf("balancer upstream keeps nginx's default connection cache:\n%s", balancer)
		}
	}
	for _, l := range originLayers(p.WithDefaults()) {
		layer := originLayerServer(t, conf, l.Socket)
		module := "proxy"
		if l.Protocol == protocolGRPC {
			module = "grpc"
		}
		for _, want := range []string{
			`set $edgeweir_ssl_name "";`,
			module + "_ssl_name $edgeweir_ssl_name;",
			module + "_ssl_server_name on;",
		} {
			if !strings.Contains(layer, want) {
				t.Errorf("origin layer %s lacks %q", l.Name, want)
			}
		}
		wants := []string{module + "_ssl_verify off;"}
		if l.Verify {
			wants = []string{module + "_ssl_verify on;", module + "_ssl_trusted_certificate /etc/edgeweir/origin-ca.pem;"}
		}
		for _, want := range wants {
			if !strings.Contains(layer, want) {
				t.Errorf("origin layer %s lacks %q", l.Name, want)
			}
		}
	}
}

// TestOriginLayerSocketDefaults: the HTTP/2 and gRPC origin layers listen
// next to the origin socket unless set; OriginLayerSockets lists all six
// (the agent removes stale ones before nginx starts).
func TestOriginLayerSocketDefaults(t *testing.T) {
	p := params()
	want := []string{
		"/run/edgeweir-node/origin.sock", "/run/edgeweir-node/origin-noverify.sock",
		"/run/edgeweir-node/origin-h2.sock", "/run/edgeweir-node/origin-noverify-h2.sock",
		"/run/edgeweir-node/origin-grpc.sock", "/run/edgeweir-node/origin-noverify-grpc.sock",
	}
	if got := p.OriginLayerSockets(); !reflect.DeepEqual(got, want) {
		t.Fatalf("origin layer sockets = %v, want %v", got, want)
	}
	p.OriginSocketGRPC = "/srv/sockets/grpc.sock"
	if got := p.OriginLayerSockets()[4]; got != "/srv/sockets/grpc.sock" {
		t.Fatalf("explicit gRPC socket replaced: %s", got)
	}
}

// TestRenderOriginLayerProtocols: the HTTP/1.1 layers proxy with
// HTTP/1.1 (WebSocket upgrades included) through edgeweir_balancer, the
// HTTP/2 layers with proxy_http_version 2 through edgeweir_balancer_h2 and
// no hop-by-hop headers, and the gRPC layers accept HTTP/2 from the edge,
// lift the body size limit and pass the requests on with grpc_pass
// (grpcs for HTTPS origins) through edgeweir_balancer_grpc.
func TestRenderOriginLayerProtocols(t *testing.T) {
	p := params()
	got, err := Render(p, configir.Bootstrap(80))
	if err != nil {
		t.Fatal(err)
	}
	conf := string(got)
	if !strings.Contains(conf, "map $edgeweir_upstream_scheme $edgeweir_grpc_scheme {\n        https   grpcs;\n        default grpc;\n    }") {
		t.Error("gRPC scheme map missing")
	}
	for _, l := range originLayers(p.WithDefaults()) {
		layer := originLayerServer(t, conf, l.Socket)
		var wants, unwanted []string
		switch l.Protocol {
		case protocolHTTP1:
			wants = []string{
				"proxy_pass $edgeweir_upstream_scheme://edgeweir_balancer$edgeweir_upstream_uri;",
				"proxy_http_version 1.1;",
				"proxy_set_header Connection $edgeweir_origin_connection;",
				"proxy_set_header Upgrade $http_upgrade;",
			}
			unwanted = []string{"http2 on;", "grpc_", "client_max_body_size"}
		case protocolHTTP2:
			wants = []string{
				"proxy_pass $edgeweir_upstream_scheme://edgeweir_balancer_h2$edgeweir_upstream_uri;",
				"proxy_http_version 2;",
				"proxy_set_header Host $edgeweir_upstream_host;",
			}
			unwanted = []string{"http2 on;", "grpc_", "Connection", "Upgrade", "client_max_body_size"}
		case protocolGRPC:
			wants = []string{
				"http2 on;",
				"client_max_body_size 0;",
				"grpc_pass $edgeweir_grpc_scheme://edgeweir_balancer_grpc;",
				"grpc_set_header Host $edgeweir_upstream_host;",
				`grpc_set_header X-Edgeweir-Site "";`,
				"grpc_next_upstream_tries 5;",
				"grpc_next_upstream error timeout http_502 http_503 http_504;",
				"grpc_next_upstream error timeout;",
			}
			unwanted = []string{"proxy_", "Connection", "Upgrade"}
		}
		wants = append(wants, `access_by_lua_block { require("edgeweir.origin").access() }`,
			`header_filter_by_lua_block { require("edgeweir.origin").header_filter() }`,
			`log_by_lua_block { require("edgeweir.origin").log() }`)
		for _, want := range wants {
			if !strings.Contains(layer, want) {
				t.Errorf("origin layer %s lacks %q", l.Name, want)
			}
		}
		for _, u := range unwanted {
			if strings.Contains(layer, u) {
				t.Errorf("origin layer %s has %q", l.Name, u)
			}
		}
		up := section(t, conf, "upstream "+l.Name+" {", "}")
		if !strings.Contains(up, "server unix:"+l.Socket+";") {
			t.Errorf("upstream %s does not reach its socket:\n%s", l.Name, up)
		}
		// Edge -> origin layer without keep-alive, but for gRPC: a failure
		// on a reused connection would be retried as a second trip to the
		// origin, also when the origin layer closes it for stale-if-error.
		if keep := !strings.Contains(up, "keepalive 0;"); keep != (l.Protocol == protocolGRPC) {
			t.Errorf("upstream %s keeps connections: %v", l.Name, keep)
		}
	}
}

// TestRenderEdgeGRPC: every edge server hands gRPC requests to the origin
// layer with grpc_pass from @edgeweir_grpc, which is never cached, lifts
// the body size limit and turns off the compression its server enables;
// every edge location / declares the context reference the hand-over
// needs.
func TestRenderEdgeGRPC(t *testing.T) {
	got, err := Render(params(), compressionPlan())
	if err != nil {
		t.Fatal(err)
	}
	conf := string(got)
	servers := strings.Count(conf, `access_by_lua_block { require("edgeweir.router").access() }`)
	if n := strings.Count(conf, "            set $edgeweir_ctx_ref \"\";\n            access_by_lua_block { require(\"edgeweir.router\").access() }"); n != servers || n == 0 {
		t.Errorf("%d of %d edge locations declare $edgeweir_ctx_ref", n, servers)
	}
	grpc := locations(conf)["@edgeweir_grpc"]
	if len(grpc) != servers {
		t.Fatalf("%d gRPC locations for %d edge servers", len(grpc), servers)
	}
	compressed := 0
	for _, body := range grpc {
		for _, want := range []string{
			"client_max_body_size 0;",
			`access_by_lua_block { require("edgeweir.router").grpc_access() }`,
			"grpc_pass grpc://$edgeweir_origin_layer;",
			"grpc_set_header Host $host;",
			"grpc_set_header X-Forwarded-For $proxy_add_x_forwarded_for;",
			"grpc_set_header CDN-Loop $edgeweir_cdn_loop;",
			"grpc_set_header X-Edgeweir-Site $edgeweir_site;",
			"grpc_set_header X-Edgeweir-Origin $edgeweir_origin_override;",
			`header_filter_by_lua_block { require("edgeweir.router").header_filter(true) }`,
			`log_by_lua_block { require("edgeweir.stats").log(true) }`,
		} {
			if !strings.Contains(body, want) {
				t.Errorf("gRPC location lacks %q:\n%s", want, body)
			}
		}
		for _, unwanted := range []string{"proxy_cache", "slice", "proxy_pass", "modsecurity"} {
			if strings.Contains(body, unwanted) {
				t.Errorf("gRPC location has %q", unwanted)
			}
		}
		if strings.Contains(body, "gzip off;") && strings.Contains(body, "brotli off;") && strings.Contains(body, "zstd off;") {
			compressed++
		}
	}
	// The servers of all.test (one per listener) compress with all three.
	if compressed != 2 {
		t.Errorf("%d gRPC locations turn every coding off, want 2", compressed)
	}
}

// TestRenderGRPCSitesTakeHTTP2: while a site proxies gRPC, the plain
// listeners take h2c and that site's servers enable HTTP/2 on every
// listener, whatever its HTTPS settings say; other servers keep theirs.
func TestRenderGRPCSitesTakeHTTP2(t *testing.T) {
	plan := &configir.Plan{
		Listeners:  []configir.Listener{{Port: 80}, {Port: 443, TLS: true}},
		CacheZones: []configir.CacheZone{{Name: "default", MaxSizeMB: 1024, KeysZoneMB: 16, InactiveSeconds: 3600}},
		Sites: []configir.Site{
			tlsSite("grpc", "grpc.test", configir.TLSOptions{}),
			tlsSite("web", "web.test", configir.TLSOptions{}),
		},
	}
	plan.Sites[0].OriginHTTP2, plan.Sites[0].GRPC = true, true
	got, err := Render(params(), plan)
	if err != nil {
		t.Fatal(err)
	}
	h2 := edgeHTTP2(string(got))
	want := map[string]bool{
		"80 _": true, "443 _": false,
		"80 grpc.test": true, "443 grpc.test": true,
		"80 web.test": false, "443 web.test": false,
	}
	if !maps.Equal(h2, want) {
		t.Fatalf("HTTP/2 by listener and server = %v, want %v", h2, want)
	}
	plan.Sites[0].GRPC = false
	if got, err = Render(params(), plan); err != nil {
		t.Fatal(err)
	}
	for server, on := range edgeHTTP2(string(got)) {
		if on {
			t.Errorf("without gRPC sites, %s enables HTTP/2", server)
		}
	}
}

// edgeHTTP2 maps the public edge servers ("<port> <server_name>") to
// whether they enable HTTP/2.
func edgeHTTP2(conf string) map[string]bool {
	out := map[string]bool{}
	for _, block := range strings.Split(conf, "\n    server {\n")[1:] {
		block, _, _ = strings.Cut(block, "\n    }\n")
		listen := regexp.MustCompile(`(?m)^\s*listen (\d+)`).FindStringSubmatch(block)
		name := regexp.MustCompile(`(?m)^\s*server_name ([^;]+);`).FindStringSubmatch(block)
		if listen == nil || name == nil {
			continue // unix sockets
		}
		out[listen[1]+" "+name[1]] = strings.Contains(block, "\n        http2 on;\n")
	}
	return out
}

// originLayerServer returns the server block of the origin layer that
// listens on socket.
func originLayerServer(t *testing.T, conf, socket string) string {
	t.Helper()
	return section(t, conf, "listen unix:"+socket+";", "\n    }\n")
}

// TestRenderOriginLayerUpstreamsKeepNoConnections: the edge layer's
// upstreams to the origin layer turn off nginx's default connection cache
// (nginx >= 1.29.7). A request that fails on a cached connection is tried
// again without using up a try, so a connection the origin layer closes on
// purpose (stale-if-error) would cost another trip to the origin.
func TestRenderOriginLayerUpstreamsKeepNoConnections(t *testing.T) {
	got, err := Render(params(), configir.Bootstrap(80))
	if err != nil {
		t.Fatal(err)
	}
	conf := string(got)
	for _, name := range []string{"edgeweir_origin_verify", "edgeweir_origin_noverify"} {
		upstream := section(t, conf, "upstream "+name+" {", "}")
		if !strings.Contains(upstream, "keepalive 0;") {
			t.Errorf("%s keeps nginx's default connection cache:\n%s", name, upstream)
		}
	}
}

// section returns the text from start up to the first end after it.
func section(t *testing.T, s, start, end string) string {
	t.Helper()
	i := strings.Index(s, start)
	if i < 0 {
		t.Fatalf("%q not found", start)
	}
	j := strings.Index(s[i:], end)
	if j < 0 {
		t.Fatalf("%q not closed", start)
	}
	return s[i : i+j+len(end)]
}

// TestRenderPurgeDictSize: the purge marker store size comes from
// --purge-dict-mb.
func TestRenderPurgeDictSize(t *testing.T) {
	p := params()
	p.PurgeDictMB = 128
	got, err := Render(p, configir.Bootstrap(80))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(got), "lua_shared_dict edgeweir_purge 128m;") {
		t.Fatal("purge dict size not rendered")
	}
}

// TestRenderBanStore: --ban-dict-mb sizes edgeweir_bans and --ban-capacity
// reaches edgeweir.bans through init_by_lua.
func TestRenderChallengeAndCCStores(t *testing.T) {
	got, err := Render(params(), configir.Bootstrap(80))
	if err != nil {
		t.Fatal(err)
	}
	for _, want := range []string{"lua_shared_dict edgeweir_challenge 8m;", "lua_shared_dict edgeweir_cc 32m;"} {
		if !strings.Contains(string(got), want) {
			t.Errorf("default %q not rendered", want)
		}
	}
	p := params()
	p.CCDictMB, p.ChallengeDictMB = 128, 16
	if got, err = Render(p, configir.Bootstrap(80)); err != nil {
		t.Fatal(err)
	}
	for _, want := range []string{"lua_shared_dict edgeweir_challenge 16m;", "lua_shared_dict edgeweir_cc 128m;"} {
		if !strings.Contains(string(got), want) {
			t.Errorf("%q not rendered", want)
		}
	}
	for _, bad := range []func(*Params){func(p *Params) { p.CCDictMB = -1 }, func(p *Params) { p.ChallengeDictMB = 65537 }} {
		p := params()
		bad(&p)
		if _, err := Render(p, configir.Bootstrap(80)); err == nil {
			t.Error("out-of-range store size accepted")
		}
	}
}

func TestRenderBanStore(t *testing.T) {
	p := params()
	p.BanDictMB, p.BanCapacity = 64, 250000
	got, err := Render(p, configir.Bootstrap(80))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(got), "lua_shared_dict edgeweir_bans 64m;") {
		t.Error("ban dict size not rendered")
	}
	if !strings.Contains(string(got), "ban_capacity = 250000,") {
		t.Error("ban capacity not rendered")
	}
}

// TestRenderedSharedDictsAreReservedZoneNames: every lua_shared_dict that
// nginx.conf declares is refused as a cache zone name. nginx keeps all
// shared memory zones in one namespace, so a keys_zone with the same name
// fails `nginx -t` and the node would reject every revision.
func TestRenderedSharedDictsAreReservedZoneNames(t *testing.T) {
	conf, err := Render(params(), configir.Bootstrap(80))
	if err != nil {
		t.Fatal(err)
	}
	dicts := regexp.MustCompile(`(?m)^\s*lua_shared_dict\s+(\S+)\s`).FindAllSubmatch(conf, -1)
	if len(dicts) < 5 {
		t.Fatalf("found %d lua_shared_dict directives, want at least 5", len(dicts))
	}
	for _, m := range dicts {
		name := string(m[1])
		plan, err := configir.Build(&nodev1.NodeConfig{
			CacheZones: []*nodev1.CacheZone{{Name: name}, {Name: "main"}},
		}, configir.Options{DefaultPort: 80})
		if err != nil {
			t.Fatal(err)
		}
		for _, z := range plan.CacheZones {
			if z.Name == name {
				t.Errorf("cache zone %q accepted, but nginx.conf declares lua_shared_dict %s", name, name)
			}
		}
		if _, err := Render(params(), plan); err != nil {
			t.Errorf("cache zone %q: %v", name, err)
		}
	}
}

// TestRenderProxyProtocolRealIP: behind a PROXY protocol listener the
// client address from the header is $remote_addr (what origins and logs
// see); plain listeners keep the peer address. The local edge socket for
// prefetches never expects the PROXY protocol.
func TestRenderProxyProtocolRealIP(t *testing.T) {
	plan := &configir.Plan{
		Listeners:  []configir.Listener{{Port: 80}, {Port: 8080, ProxyProtocol: true}},
		CacheZones: []configir.CacheZone{{Name: "z", MaxSizeMB: 1, KeysZoneMB: 1, InactiveSeconds: 60}},
	}
	got, err := Render(params(), plan)
	if err != nil {
		t.Fatal(err)
	}
	conf := string(got)
	plain := section(t, conf, "listen 80 default_server;", "location /")
	pp := section(t, conf, "listen 8080 default_server proxy_protocol;", "location /")
	local := section(t, conf, "listen unix:/run/edgeweir-node/edge.sock default_server;", "location /")
	for _, want := range []string{"set_real_ip_from 0.0.0.0/0;", "set_real_ip_from ::/0;", "real_ip_header proxy_protocol;"} {
		if !strings.Contains(pp, want) {
			t.Errorf("PROXY protocol listener lacks %q", want)
		}
		if strings.Contains(plain, want) || strings.Contains(local, want) {
			t.Errorf("plain or local listener has %q", want)
		}
	}
	if strings.Contains(local, "proxy_protocol") {
		t.Error("local edge socket expects the PROXY protocol")
	}
}

// TestRenderConfID: every rendered file carries the id the data plane
// reports after loading it (reload verification); equal settings give
// equal ids, structural changes new ones.
func TestRenderConfID(t *testing.T) {
	a, _ := Render(params(), configir.Bootstrap(80))
	b, _ := Render(params(), configir.Bootstrap(80))
	c, _ := Render(params(), configir.Bootstrap(8080))
	idA, idC := ConfID(a), ConfID(c)
	if len(idA) != 16 || strings.Trim(idA, "0123456789abcdef") != "" {
		t.Fatalf("conf id = %q", idA)
	}
	if ConfID(b) != idA || !bytes.Equal(a, b) {
		t.Fatal("same settings, different files or ids")
	}
	if idC == idA {
		t.Fatal("listener change kept the id")
	}
	if ConfID([]byte("worker_processes 1;")) != "" {
		t.Fatal("id found in a file without one")
	}
}

// TestRenderTagStore: --tag-dict-mb sizes edgeweir_tags, the Cache-Tag
// index.
func TestRenderTagStore(t *testing.T) {
	got, err := Render(params(), configir.Bootstrap(80))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(got), "lua_shared_dict edgeweir_tags 64m;") {
		t.Error("default tag dict size not rendered")
	}
	p := params()
	p.TagDictMB = 256
	if got, err = Render(p, configir.Bootstrap(80)); err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(got), "lua_shared_dict edgeweir_tags 256m;") {
		t.Error("tag dict size not rendered")
	}
	for _, size := range []int{-1, 65537} {
		p := params()
		p.TagDictMB = size
		if _, err := Render(p, configir.Bootstrap(80)); err == nil {
			t.Errorf("tag dict size %d accepted", size)
		}
	}
}

// TestRenderSitesStore: --sites-dict-mb sizes edgeweir_sites, which holds
// the current and the previous site table (error page templates
// included).
func TestRenderSitesStore(t *testing.T) {
	got, err := Render(params(), configir.Bootstrap(80))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(got), "lua_shared_dict edgeweir_sites 64m;") {
		t.Error("default sites dict size not rendered")
	}
	p := params()
	p.SitesDictMB = 512
	if got, err = Render(p, configir.Bootstrap(80)); err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(got), "lua_shared_dict edgeweir_sites 512m;") {
		t.Error("sites dict size not rendered")
	}
	for _, size := range []int{-1, 65537} {
		p := params()
		p.SitesDictMB = size
		if _, err := Render(p, configir.Bootstrap(80)); err == nil {
			t.Errorf("sites dict size %d accepted", size)
		}
	}
}

// locations returns the bodies of the location blocks of conf by name
// ("/" of every server, "@edgeweir_waf_<limit>"), in order.
func locations(conf string) map[string][]string {
	out := map[string][]string{}
	lines := strings.Split(conf, "\n")
	for i := 0; i < len(lines); i++ {
		line := strings.TrimSpace(lines[i])
		if !strings.HasPrefix(line, "location ") || !strings.HasSuffix(line, "{") {
			continue
		}
		name := strings.TrimSpace(strings.TrimSuffix(strings.TrimPrefix(line, "location "), "{"))
		depth, body := 1, []string{}
		for i++; i < len(lines) && depth > 0; i++ {
			depth += strings.Count(lines[i], "{") - strings.Count(lines[i], "}")
			body = append(body, lines[i])
		}
		i--
		out[name] = append(out[name], strings.Join(body, "\n"))
	}
	return out
}

// TestRenderEdgeRequestIDsAndHiddenHeaders: every edge location answers
// with the request id (also on errors), passes it to the origin layer and
// never forwards the origin's id, Cache-Tag or the affinity announcement;
// body filters exist only where error pages replace bodies (the origin
// layer and the CRS locations), never in the edge layer's location /.
func TestRenderEdgeRequestIDsAndHiddenHeaders(t *testing.T) {
	p := params()
	p.ModSecurityModule = "/usr/lib/edgeweir-openresty/modules/ngx_http_modsecurity_module.so"
	plan := wafPlan()
	got, err := Render(p, plan)
	if err != nil {
		t.Fatal(err)
	}
	conf := string(got)
	if !strings.Contains(conf, "map $http_x_request_id $edgeweir_request_id {\n        default $request_id;\n        \"~^[A-Za-z0-9._:-]{8,128}$\" $http_x_request_id;\n    }") {
		t.Error("request id map missing")
	}
	locs := locations(conf)
	var edge, origin []string
	for _, body := range locs["/"] {
		switch {
		case strings.Contains(body, "edgeweir.router\").access()"):
			edge = append(edge, body)
		case strings.Contains(body, "edgeweir.origin\").access()"):
			origin = append(origin, body)
		}
	}
	waf := append(slices.Clone(locs["@edgeweir_waf_0"]), locs["@edgeweir_waf_131072"]...)
	grpc := locs["@edgeweir_grpc"]
	if len(edge) == 0 || len(origin) != 6 || len(waf) == 0 || len(grpc) != len(edge) {
		t.Fatalf("locations: %d edge, %d origin, %d CRS, %d gRPC", len(edge), len(origin), len(waf), len(grpc))
	}
	for _, body := range slices.Concat(edge, waf, grpc) {
		module := "proxy"
		if strings.Contains(body, "grpc_pass") {
			module = "grpc"
		}
		for _, want := range []string{
			"add_header X-Request-Id $edgeweir_request_id always;",
			module + "_set_header X-Request-Id $edgeweir_request_id;",
			module + "_hide_header X-Request-Id;",
			module + "_hide_header Cache-Tag;",
			module + "_hide_header X-Edgeweir-Affinity;",
		} {
			if !strings.Contains(body, want) {
				t.Errorf("edge location lacks %q", want)
			}
		}
	}
	for _, body := range edge {
		if strings.Contains(body, "body_filter") {
			t.Error("the edge layer's location / has a body filter")
		}
	}
	for _, body := range waf {
		if !strings.Contains(body, `body_filter_by_lua_block { require("edgeweir.router").body_filter() }`) {
			t.Error("a CRS location lacks the error page body filter")
		}
	}
	for _, body := range origin {
		if !strings.Contains(body, `body_filter_by_lua_block { require("edgeweir.origin").body_filter() }`) {
			t.Error("an origin layer location lacks the error page body filter")
		}
		if strings.Contains(body, "X-Request-Id") {
			t.Error("the origin layer touches X-Request-Id (it forwards the edge's)")
		}
	}
}

// TestRenderErrorPages: nginx's own errors go to error pages in every edge
// server (also from the CRS locations, which have no error_page of their
// own) and in both origin layers: to the named location, or, for requests
// without a URI yet, to an internal location no client path reaches. The
// control API keeps nginx's answers.
func TestRenderErrorPages(t *testing.T) {
	p := params()
	p.ModSecurityModule = "/usr/lib/edgeweir-openresty/modules/ngx_http_modsecurity_module.so"
	plan := wafPlan()
	plan.Listeners = append(plan.Listeners, configir.Listener{Port: 443, TLS: true})
	got, err := Render(p, plan)
	if err != nil {
		t.Fatal(err)
	}
	conf := string(got)
	if !strings.Contains(conf, "map $uri $edgeweir_error_page {\n        \"\"      /./edgeweir-error;\n        default @edgeweir_error;\n    }") {
		t.Error("error page target map missing")
	}
	const (
		edgeDirectives = "error_page 400 413 414 500 502 504 $edgeweir_error_page;\n" +
			"        error_page 494 =494 $edgeweir_error_page;\n        error_page 497 =497 $edgeweir_error_page;\n"
		originDirectives = "error_page 400 413 414 500 $edgeweir_error_page;\n        error_page 494 =494 $edgeweir_error_page;\n"
	)
	edgeServers := strings.Count(conf, `access_by_lua_block { require("edgeweir.router").access() }`)
	if n := strings.Count(conf, edgeDirectives); n != edgeServers || n != 4 {
		t.Errorf("%d of %d edge servers hand nginx's errors to error pages", n, edgeServers)
	}
	if n := strings.Count(conf, originDirectives); n != 6 {
		t.Errorf("%d origin layers hand nginx's errors to error pages", n)
	}
	if n := len(regexp.MustCompile(`(?m)^\s*error_page\s`).FindAllString(conf, -1)); n != 3*edgeServers+2*6 {
		t.Errorf("%d error_page directives: one set per server only (none in the CRS or gRPC locations or the control API)", n)
	}
	control := section(t, conf, "listen unix:"+p.ControlSocket+";", "\n    }\n")
	if strings.Contains(control, "error_page") || strings.Contains(control, "edgeweir_error") {
		t.Error("the control API has error pages")
	}
	locs := locations(conf)
	named, internal := locs["@edgeweir_error"], locs["= /./edgeweir-error"]
	if len(named) != edgeServers+6 || len(internal) != edgeServers+6 {
		t.Fatalf("%d named and %d internal error locations for %d servers", len(named), len(internal), edgeServers+6)
	}
	const (
		edgeHandler   = `content_by_lua_block { require("edgeweir.router").error_page() }`
		originHandler = `content_by_lua_block { require("edgeweir.origin").error_page() }`
	)
	for i, body := range append(slices.Clone(named), internal...) {
		edge := strings.Contains(body, edgeHandler)
		if edge == strings.Contains(body, originHandler) {
			t.Fatalf("error location without one handler:\n%s", body)
		}
		if edge && !strings.Contains(body, "uninitialized_variable_warn off;") {
			t.Error("an edge error location warns about the variables location / did not set")
		}
		// Only the edge's named location counts requests (from location /
		// or a CRS location; requests without a URI have no site).
		counts := strings.Contains(body, `log_by_lua_block { require("edgeweir.stats").log(true) }`)
		if counts != (edge && i < len(named)) {
			t.Errorf("error location counts requests: %v\n%s", counts, body)
		}
		if internalLoc := i >= len(named); internalLoc != strings.Contains(body, "internal;") {
			t.Errorf("error location internal: %v\n%s", internalLoc, body)
		}
		for _, banned := range []string{"proxy_pass", "modsecurity on"} {
			if strings.Contains(body, banned) {
				t.Errorf("error location has %q", banned)
			}
		}
		if regexp.MustCompile(`(?m)^\s*error_page\s`).MatchString(body) {
			t.Error("error location has its own error_page")
		}
	}
	if n := strings.Count(strings.Join(named, ""), edgeHandler); n != edgeServers {
		t.Errorf("%d edge named error locations for %d edge servers", n, edgeServers)
	}
}
