package render

import (
	"bytes"
	"flag"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"github.com/edgeweir/edgeweir-node/internal/configir"
)

var update = flag.Bool("update", false, "rewrite golden files")

func params() Params {
	return Params{
		Prefix:        "/var/lib/edgeweir-node/nginx",
		LuaDir:        "/usr/share/edgeweir-node/lua",
		CacheDir:      "/var/cache/edgeweir-node",
		ControlSocket: "/run/edgeweir-node/control.sock",
		OriginSocket:  "/run/edgeweir-node/origin.sock",
		ResolvConf:    "/etc/resolv.conf",
		Resolvers:     []string{"127.0.0.11"},
	}
}

func golden(t *testing.T, name string, got []byte) {
	t.Helper()
	path := filepath.Join("testdata", name)
	if *update {
		if err := os.WriteFile(path, got, 0o644); err != nil {
			t.Fatal(err)
		}
	}
	want, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read golden file (run with -update): %v", err)
	}
	if !bytes.Equal(got, want) {
		t.Fatalf("%s differs from golden file; run `go test ./internal/render -update` and review the diff\n--- got ---\n%s", name, got)
	}
}

func TestRenderBootstrapGolden(t *testing.T) {
	got, err := Render(params(), configir.Bootstrap(80))
	if err != nil {
		t.Fatal(err)
	}
	golden(t, "bootstrap.conf.golden", got)
}

func TestRenderFullGolden(t *testing.T) {
	p := params()
	p.Resolvers = []string{"10.0.0.2", "[2001:db8::53]"}
	p.ResolverIPv6 = true
	p.ListenIPv6 = true
	p.WorkerConnections = 8192
	plan := &configir.Plan{
		Listeners: []configir.Listener{
			{Port: 80, HTTP2: true},
			{Port: 8080, ProxyProtocol: true},
		},
		CacheZones: []configir.CacheZone{
			{Name: "hot", MaxSizeMB: 2048, KeysZoneMB: 32, InactiveSeconds: 86400},
			{Name: "images", MaxSizeMB: 10240, KeysZoneMB: 64, InactiveSeconds: 3600},
		},
		Sites: []configir.Site{{ID: "must-not-appear-in-nginx-conf"}},
	}
	got, err := Render(p, plan)
	if err != nil {
		t.Fatal(err)
	}
	if bytes.Contains(got, []byte("must-not-appear")) {
		t.Fatal("site data leaked into nginx.conf")
	}
	golden(t, "full.conf.golden", got)
}

func TestRenderIgnoresSitesAndRevision(t *testing.T) {
	a := configir.Bootstrap(80)
	b := configir.Bootstrap(80)
	b.Revision = 42
	b.ContentHash = "abc"
	b.Sites = []configir.Site{{ID: "s1", Domains: []configir.Domain{{Name: "a.test"}}}}
	ra, _ := Render(params(), a)
	rb, _ := Render(params(), b)
	if !bytes.Equal(ra, rb) {
		t.Fatal("site or revision changes altered nginx.conf (would trigger needless reloads)")
	}
	c := configir.Bootstrap(8080)
	rc, _ := Render(params(), c)
	if bytes.Equal(ra, rc) {
		t.Fatal("listener change did not alter nginx.conf")
	}
}

func TestRenderRejectsUnsafeInput(t *testing.T) {
	bad := []func(*Params){
		func(p *Params) { p.Prefix = "relative/path" },
		func(p *Params) { p.LuaDir = "/usr/share/lua; include /etc/passwd" },
		func(p *Params) { p.ControlSocket = "/run/x sock" },
		func(p *Params) { p.Resolvers = []string{"8.8.8.8 valid=1s"} },
		func(p *Params) { p.Resolvers = []string{"dns.example"} },
		func(p *Params) { p.WorkerProcesses = "auto;" },
		func(p *Params) { p.User = "root; daemon on" },
	}
	for i, mutate := range bad {
		p := params()
		mutate(&p)
		if _, err := Render(p, configir.Bootstrap(80)); err == nil {
			t.Errorf("case %d: unsafe params accepted", i)
		}
	}
	plan := configir.Bootstrap(80)
	plan.CacheZones[0].Name = "x; evil"
	if _, err := Render(params(), plan); err == nil {
		t.Error("unsafe zone name accepted")
	}
	if _, err := Render(params(), &configir.Plan{}); err == nil {
		t.Error("empty plan accepted")
	}
}

func TestParseResolvConf(t *testing.T) {
	in := `# Generated by Docker
search example.internal
nameserver 127.0.0.11
options ndots:0
nameserver 2001:4860:4860::8888
nameserver fe80::1%eth0
nameserver ::ffff:10.0.0.1
nameserver 127.0.0.11
nameserver not-an-ip
nameserver 0.0.0.0
  nameserver 1.1.1.1 # trailing comment
`
	got := ParseResolvConf(strings.NewReader(in))
	want := []string{"127.0.0.11", "[2001:4860:4860::8888]", "10.0.0.1", "1.1.1.1"}
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("ParseResolvConf = %v, want %v", got, want)
	}
}

func TestResolversFallback(t *testing.T) {
	if got := Resolvers(filepath.Join(t.TempDir(), "missing")); !reflect.DeepEqual(got, []string{"127.0.0.1"}) {
		t.Fatalf("missing file: %v", got)
	}
	empty := filepath.Join(t.TempDir(), "resolv.conf")
	if err := os.WriteFile(empty, []byte("search x\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if got := Resolvers(empty); !reflect.DeepEqual(got, []string{"127.0.0.1"}) {
		t.Fatalf("no nameservers: %v", got)
	}
}
